#!/bin/bash
# 测试 ttyd 1.7.4 的 WebSocket 协议

echo "🧪 测试 ttyd WebSocket 协议..."
echo ""
echo "根据 ttyd 1.7.4 源码，客户端发送的消息类型："
echo "  '0' = INPUT (客户端输入)"
echo "  '1' = PING"
echo "  '2' = RESIZE_TERMINAL"
echo ""
echo "我们当前的实现："
echo "  SendLine: \"0\" + line + \"\\n\""
echo ""
echo "这应该是正确的格式。"
echo ""
echo "请在远程服务器上运行以下命令来验证修复："
echo ""
echo "1. 重新编译并部署:"
echo "   cd ~/huixin/aiops/aiops-qproxy-v2.4"
echo "   git pull  # 或者上传新的二进制文件"
echo "   ./scripts/deploy-real-q.sh"
echo ""
echo "2. 测试:"
echo "   ./scripts/test-sdn5.sh"
echo ""
echo "3. 查看 ttyd 日志，确认不再有 'ignored unknown message type' 错误:"
echo "   tail -50 logs/ttyd-q.log | grep -i 'ignored\\|error\\|warn'"
echo ""

